# https://taskfile.dev

version: "3"

tasks:
  default:
    - task: help

  routes:
    - mix phx.routes -r Ecomerce.Router

  reset:
    cmds:
      - task: clean
      - task: setup

  clean:
    - mix clean
    - mix ecto.drop
    - rm -rf ./assets/node_modules
    - rm -rf ./uploads

  migrate:
    cmds:
      - mix ecto.migrate

  server:
    deps: [migrate]
    cmds:
      - mix phx.server

  iex.server:
    deps: [migrate]
    cmds:
      - iex -S mix phx.server

  setup:
    cmds:
      - mix deps.get
      - mix compile
      - mix ecto.setup
      - npm install --prefix assets

  seed:
    - mix run priv/repo/seeds.exs

  iex:
    deps: [migrate]
    cmds:
      - iex -S mix

  test:
    cmds:
      - mix test

  test.wip:
    cmds:
      - mix test --only wip

  help:
    - echo "Hey"
